# File project config
model:
  input_dim: 63
  hidden_dim: [512, 256, 128, 64]
  dropout_rate: 0.4
  num_classes: 10 # Số lớp cho cử chỉ tay

training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 100
  validation_split: 0.2
  patience: 10
  model_save_path: "src/models/hand_gesture_model_camera.pth"
  log_interval: 10

data:
  label_file: "src/data/processed/hand_gesture_labels.csv"
  train_file: "src/data/processed/hand_gesture_camera.csv"
